"""printer_model.modele_override

Revision ID: 1e81bda359ac
Revises: d64f4d118cf3
Create Date: 2026-08-18 16:20:53.841429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e81bda359ac'
down_revision: Union[str, None] = 'd64f4d118cf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('printer_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modele_override', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('printer_model', schema=None) as batch_op:
        batch_op.drop_column('modele_override')

    # ### end Alembic commands ###
