"""PIN-Anmeldung statt Badge

Revision ID: c7adc3db606b
Revises: 1e81bda359ac
Create Date: 2026-08-20 13:51:08.753880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7adc3db606b'
down_revision: Union[str, None] = '1e81bda359ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('pin_change_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('echecs', sa.Integer(), nullable=False,
                                      server_default='0'))
        batch_op.add_column(sa.Column('bloque_jusqua', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_app_user_username', ['username'])
        batch_op.drop_column('salto_hash')
        batch_op.drop_column('mycard_hash')

    with op.batch_alter_table('movement', schema=None) as batch_op:
        batch_op.drop_column('badge_type')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('badge_type', sa.VARCHAR(length=10), nullable=True))

    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mycard_hash', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('salto_hash', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_constraint('uq_app_user_username', type_='unique')
        batch_op.drop_column('bloque_jusqua')
        batch_op.drop_column('echecs')
        batch_op.drop_column('pin_change_at')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
