"""schema initial

Revision ID: d2570686b109
Revises: 
Create Date: 2026-07-31 20:02:53.258299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2570686b109'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_setting',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=160), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('mycard_hash', sa.String(length=64), nullable=True),
    sa.Column('salto_hash', sa.String(length=64), nullable=True),
    sa.Column('pin_hash', sa.String(length=255), nullable=True),
    sa.Column('actif', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mycard_hash'),
    sa.UniqueConstraint('salto_hash')
    )
    op.create_table('consumable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=False),
    sa.Column('designation', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('couleur', sa.String(length=10), nullable=True),
    sa.Column('marque', sa.String(length=120), nullable=True),
    sa.Column('ean', sa.String(length=40), nullable=True),
    sa.Column('emplacement', sa.String(length=60), nullable=True),
    sa.Column('seuil_alerte', sa.Integer(), nullable=False),
    sa.Column('actif', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('printer_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marque', sa.String(length=120), nullable=False),
    sa.Column('modele', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('categorie', sa.String(length=120), nullable=True),
    sa.Column('categorie_id', sa.Integer(), nullable=True),
    sa.Column('marque_override', sa.String(length=120), nullable=True),
    sa.Column('mapping_ok', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('marque', 'modele', name='uq_model_marque_modele'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('delivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fournisseur', sa.String(length=255), nullable=True),
    sa.Column('bon_livraison', sa.String(length=120), nullable=True),
    sa.Column('date_livr', sa.Date(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rows_total', sa.Integer(), nullable=False),
    sa.Column('rows_kept', sa.Integer(), nullable=False),
    sa.Column('rows_state_filtered', sa.Integer(), nullable=False),
    sa.Column('rows_category_filtered', sa.Integer(), nullable=False),
    sa.Column('nb_created', sa.Integer(), nullable=False),
    sa.Column('nb_updated', sa.Integer(), nullable=False),
    sa.Column('nb_absent', sa.Integer(), nullable=False),
    sa.Column('nb_new_models', sa.Integer(), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_consumable',
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('consumable_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['consumable_id'], ['consumable.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['printer_model.id'], ),
    sa.PrimaryKeyConstraint('model_id', 'consumable_id')
    )
    op.create_table('delivery_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('consumable_id', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantite > 0', name='ck_delivery_line_qte'),
    sa.ForeignKeyConstraint(['consumable_id'], ['consumable.id'], ),
    sa.ForeignKeyConstraint(['delivery_id'], ['delivery.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('printer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_item_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('serial', sa.String(length=120), nullable=True),
    sa.Column('cgie', sa.String(length=120), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('code_entite', sa.String(length=60), nullable=True),
    sa.Column('annexe', sa.String(length=120), nullable=True),
    sa.Column('salle', sa.String(length=120), nullable=True),
    sa.Column('salle_type', sa.String(length=60), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('etat', sa.String(length=20), nullable=False),
    sa.Column('ip', sa.String(length=60), nullable=True),
    sa.Column('mac', sa.String(length=60), nullable=True),
    sa.Column('date_mise_service', sa.Date(), nullable=True),
    sa.Column('fournisseur', sa.String(length=255), nullable=True),
    sa.Column('first_seen_import', sa.Integer(), nullable=True),
    sa.Column('last_seen_import', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['first_seen_import'], ['import_run.id'], ),
    sa.ForeignKeyConstraint(['last_seen_import'], ['import_run.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['printer_model.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_item_id')
    )
    with op.batch_alter_table('printer', schema=None) as batch_op:
        batch_op.create_index('ix_printer_etat', ['etat'], unique=False)
        batch_op.create_index('ix_printer_model', ['model_id'], unique=False)

    op.create_table('movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consumable_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('motif', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('badge_type', sa.String(length=10), nullable=True),
    sa.Column('printer_id', sa.Integer(), nullable=True),
    sa.Column('delivery_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('mois', sa.String(length=7), nullable=False),
    sa.Column('annee_scolaire', sa.String(length=9), nullable=False),
    sa.ForeignKeyConstraint(['consumable_id'], ['consumable.id'], ),
    sa.ForeignKeyConstraint(['delivery_id'], ['delivery.id'], ),
    sa.ForeignKeyConstraint(['printer_id'], ['printer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movement', schema=None) as batch_op:
        batch_op.create_index('ix_mov_consumable', ['consumable_id'], unique=False)
        batch_op.create_index('ix_mov_created', ['created_at'], unique=False)
        batch_op.create_index('ix_mov_saison', ['annee_scolaire', 'mois'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movement', schema=None) as batch_op:
        batch_op.drop_index('ix_mov_saison')
        batch_op.drop_index('ix_mov_created')
        batch_op.drop_index('ix_mov_consumable')

    op.drop_table('movement')
    with op.batch_alter_table('printer', schema=None) as batch_op:
        batch_op.drop_index('ix_printer_model')
        batch_op.drop_index('ix_printer_etat')

    op.drop_table('printer')
    op.drop_table('delivery_line')
    op.drop_table('model_consumable')
    op.drop_table('import_run')
    op.drop_table('delivery')
    op.drop_table('printer_model')
    op.drop_table('consumable')
    op.drop_table('app_user')
    op.drop_table('app_setting')
    # ### end Alembic commands ###
