"""consumable.fournisseur

Revision ID: d64f4d118cf3
Revises: d2570686b109
Create Date: 2026-07-31 21:13:03.916581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd64f4d118cf3'
down_revision: Union[str, None] = 'd2570686b109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fournisseur', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumable', schema=None) as batch_op:
        batch_op.drop_column('fournisseur')

    # ### end Alembic commands ###
